org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4g

group=dev.franwdev
version=1.0.0
archive_name=lootr-teams-1.21.1

mod_name=LootrTeams
mod_author=FranwDev
mod_id=lootrteams
mod_license=MIT

minecraft_version=1.21.1
neoforge_version=21.1.65

# FTB Teams (optional, compileOnly)
ftbteams_version=2101.1.2

