modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="lootrteams"
version="${file.jarVersion}"
displayName="Lootr Teams Addon"
description="Team-based shared loot for Lootr."

[[dependencies.lootrteams]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lootrteams]]
    modId="lootr"
    type="required"
    versionRange="[1.21,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.lootrteams]]
    modId="ftbteams"
    type="optional"
    versionRange="[2101,)"
    ordering="BEFORE"
    side="BOTH"

